---
toc: true
editor:
  render-on-save: true
format:
   html:
      theme: darkly
      output-file: index.html
      table-of-contents: true
   pdf:
      colorlinks: true
      toc: false
      geometry:
        - top=10mm
        - bottom=15mm
        - left=20mm
        - right=20mm
        - heightrounded
      include-in-header:
        - text: |
            \usepackage{multicol}
            \usepackage{hyperref} 
---

# Resume | D. Stuart Bowman

\begin{multicols}{2}

Contact: 

\begin{itemize}
\item gmail: bowman.d.stuart
\item \href{https://usrse.slack.com/}{slack}
\item \href{https://github.com/buffetboy2001}{github}
\item \href{https://www.linkedin.com/in/stuart-bowman-aa2b48/}{linkedin}

\end{itemize}

\columnbreak

Technology keywords:

\begin{itemize}
\item SOLID software development
\item C++, JAVA, Python3
\item MacOs, Linux (Rocky, Raspberry Pi OS)
\item Aviation, Avionics, Flight Management System, Guidance, Navigation, Control, Robotics, Algorithms
\end{itemize}

\end{multicols}

I am:

* a member of the technical staff at the [MITRE Corporation](https://www.mitre.org);
* an aerospace engineer who loves writing scientific software for the aviation research community;
* a [research software engineer](https://us-rse.org/);
* a developer of algorithms;
* a researcher and modeler of Flight Management Systems;
* a developer of scientific simulations;
* a data analyst.

I'm always interested in opportunities that:

* deepen my simulation expertise;
* deepen my scientific expertise;
* broadens my ability to talk about science and aviation;
* uses scientific software thoughtfully for good science & reproducibility;
* pays attention to Open Science and open source software concepts.

# Research Engineer @ MITRE

My background is in the science of flight and software engineering & that has been the main focus of my work at MITRE: commercial aviation simulations. The essential work of my career has been to practice two deeply technical fields and bring them together: aerospace engineering and software engineering. I do this by building scientific simulations that enable scientifically defensible & reproducible research. 

# Publications

I enjoy writing about science; I mostly do it using computer languages. 

## Open Source

- [FIM MOPS Aircraft & Control Model](https://mitre.github.io/FMACM/): A basic civil aviation simulation that contains standard 3-DOF equations of motion, and basic control laws for a guidance path. This code is used by avionics manufacturers when testing for compliance to RTCA minimum operational standard [DO-361A](https://my.rtca.org/NC__Product?id=a1B1R00000BdQlmUAF) and documented in this [MITRE technical paper](https://www.mitre.org/publications/technical-papers/derivation-of-a-point-mass-aircraft-model-used-for-fast-time). 

- [Interval Management Sample Algorithm](https://mitre.github.io/im_sample_algorithm/): A minimum "sample" implementation of the algorithms necessary to comply with [DO-361A](https://my.rtca.org/NC__Product?id=a1B1R00000BdQlmUAF). This is used as a reference by manufacturers seeking to implement Interval Management concepts in the Flight-deck. 

## Conference, etc.

* _Analysis of the Use of Estimated Time of Arrival boradcast for Interval Management_. Air Traffic Management, 2017.
* _Closing the Loop: Testing for IM Avionics Certification_. AIAA SciTech, 2016.
* [_Minimum Drag Power-Law Shapes for Rarefied Flow_](https://arc.aiaa.org/doi/abs/10.2514/2.1743)
* [_Optimization of Low-Perigee Spacecraft Aerodynamics_](https://arc.aiaa.org/doi/abs/10.2514/2.3915)
* Thesis: _Numerical Optimization of Low-Perigee Spacecraft Shapes_, University of Maryland at College Park, May 2001.

# Extracirricular

* Robotics Instructor @ [Cornerstone Classical Academy](https://cornerstoneclassicalroanoke.org/faculty) in Roanoke, VA since 2020.
* You can find out more about me at my blog: [aerosci.dev](https://www.aerosci.dev).

# Previous Employment

**8/2004- 2/2008** | Systems Engineer | [SAIC, Inc.](https://www.saic.com/), Crystal City, VA

* Regularly perform maintenance and accreditation of physics-based, 6-DoF simulations of the Tomahawk cruise missile as an integral member of the Mission Validation Analysis team.
* Research performance concerns and prototype solutions, providing valuable support to the simulation development effort.
* Develop software tools which increase the productivity of the team, including network resource management software and IDE-style scripting software.

**7/2003 – 8/2004** | Systems Engineer | [SPARTA, Inc.](https://en.wikipedia.org/wiki/SPARTA,_Inc.), Rosslyn, VA

* Interacted with the Missile Defense National Team, producing documents and presentations which advised the government regarding existing and developing ballistic missile threats around the world.

**7/2001 – 7/2003** | Engineer | Systems Engineering Group, Inc., Columbia, MD

* Employed knowledge of aerodynamics, propulsion, and flight dynamics in the development of classified and unclassified missile models, and used those models to generate reliable data for our Naval customer.
* Maintained and streamlined a six degree-of-freedom point-mass simulation code, providing valuable support and increased functionality for the users.
* Conducted research in areas key to the missile modeling process and produced memorandums which accurately summarized the results.

**6/1999 - 6/2001** | Graduate Research Assistant | University of Maryland College Park ~ Center for Hypersonic Education and Research, College Park, MD

* Developed and designed a low-perigee spacecraft geometry model and an analytical, rarefied flow model resulting in software which calculated a spacecraft’s on- and off-design forces and moments.
* Integrated the geometry and aerodynamic flow models with a numerical, gradient-based optimizer and successfully explored the spacecraft’s design space, producing a reduced drag spacecraft shape for NASA Goddard's Geospace Electrodynamics Connections mission.

# Education

**Master of Science** | 2001 | University Of Maryland College Park

Concentration: Aerospace Engineering

Thesis: Numerical Optimization of Low-Perigee Spacecraft Shapes

Key Courses: Astrodynamics, High-Temperature Gas Dynamics, Viscous Flow, High-Speed Propulsion, Burning Theory, Computational Fluid Dynamics, Engineering Optimization, Electric Propulsion

**Bachelor of Science** | 1999 | Magna Cum Laude (3.86/4.0) | University of Maryland College Park

Concentration: Aerospace Engineering

Key Courses: Aerodynamics (Hypersonic, Compressible, Incompressible), Air-breathing Propulsion, Aircraft Performance and Control, Aircraft Design, Aircraft Structures, Technical Writing